/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfases;

import Clases.Calificar_evento;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import com.db4o.query.Query;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo.User
 */
public class Calificar extends javax.swing.JFrame {

    int calificacion = 0;
    String codigo_evento = " ";

    /**
     * Creates new form Calificar
     */
    public Calificar(String codigo) {
        initComponents();
        this.setLocationRelativeTo(null);
        txtcedula.setText(Inicio.cedula);
        this.codigo_evento = codigo;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcedula = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblemoji = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEstrella1 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 12, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcedula.setBackground(new java.awt.Color(255, 255, 255));
        txtcedula.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 930, 640));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 12, true));
        jPanel2.setForeground(new java.awt.Color(218, 183, 133));

        lblemoji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cara123.png"))); // NOI18N
        lblemoji.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("¿Que te ha parecido nuestro evento?");

        lblEstrella1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEstrella1MouseClicked(evt);
            }
        });

        lbl1.setForeground(new java.awt.Color(0, 0,0,0));
        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Estrella vacia.png"))); // NOI18N
        lbl1.setText("jLabel4");
        lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1MouseClicked(evt);
            }
        });

        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Estrella vacia.png"))); // NOI18N
        lbl2.setText("jLabel4");
        lbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl2MouseClicked(evt);
            }
        });

        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Estrella vacia.png"))); // NOI18N
        lbl3.setText("jLabel4");
        lbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl3MouseClicked(evt);
            }
        });

        lbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Estrella vacia.png"))); // NOI18N
        lbl4.setText("jLabel4");
        lbl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl4MouseClicked(evt);
            }
        });

        lbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Estrella vacia.png"))); // NOI18N
        lbl5.setText("jLabel4");
        lbl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl5MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Enviar Calificación");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblEstrella1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(lblemoji, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)))
                .addGap(225, 225, 225))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblemoji, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEstrella1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)
                        .addContainerGap(44, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 640, 410));

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida (2).png"))); // NOI18N
        jButton1.setToolTipText("DA CLICK PARA REGRESAR AL MENÚ DEL CLIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo Oficila de Eventos.PNG"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblEstrella1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEstrella1MouseClicked

    }//GEN-LAST:event_lblEstrella1MouseClicked

    private void lbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MouseClicked

        lbl1.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));
        lbl2.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));
        lbl3.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));
        lbl4.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));
        lbl5.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));

        calificacion = 1;
        lblemoji.setIcon(new ImageIcon("src\\imagenes\\Cara123.png"));

    }//GEN-LAST:event_lbl1MouseClicked

    private void lbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2MouseClicked
        lbl1.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));

        lbl2.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));
        lbl3.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));
        lbl4.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));
        lbl5.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));

        calificacion = 2;
        lblemoji.setIcon(new ImageIcon("src\\imagenes\\Cara123.png"));
    }//GEN-LAST:event_lbl2MouseClicked

    private void lbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl3MouseClicked
        lbl1.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));
        lbl2.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));
        lbl3.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));
        lbl4.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));
        lbl5.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));
        calificacion = 3;
        lblemoji.setIcon(new ImageIcon("src\\imagenes\\Cara4.png"));

    }//GEN-LAST:event_lbl3MouseClicked

    private void lbl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl4MouseClicked
        lbl1.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));
        lbl2.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));
        lbl3.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));
        lbl4.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));
        lbl5.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));

        calificacion = 4;

        lblemoji.setIcon(new ImageIcon("src\\imagenes\\Cara4.png"));

    }//GEN-LAST:event_lbl4MouseClicked

    private void lbl5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl5MouseClicked
        // TODO add your handling code here:
        lbl1.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));
        lbl2.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));
        lbl3.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));
        lbl4.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));
        lbl5.setIcon(new ImageIcon("src\\imagenes\\Estrella llena.png"));

        calificacion = 5;
        lblemoji.setIcon(new ImageIcon("src\\imagenes\\Cara5.png"));

    }//GEN-LAST:event_lbl5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ObjectContainer base = Db4o.openFile(Inicio.direccion);

        GuardarCalificacion(base, calificacion);
        base.close();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu_Cliente mc = new Menu_Cliente();
        mc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void GuardarCalificacion(ObjectContainer base, int calificacion) {

        System.out.println(codigo_evento + " " + calificacion);

        try {
            Query query = base.query();
            query.constrain(Calificar_evento.class);
            query.descend("cod_evento").orderDescending();
            ObjectSet<Calificar_evento> result = query.execute();

            int ultimoCodigo = 1;
            if (!result.isEmpty()) {
                Calificar_evento ultimoPuesto = result.next();
                ultimoCodigo = Integer.parseInt(ultimoPuesto.getCod_evento().substring(4)) + 1;
            }

            String nuevoCodigo = String.format("CAL-%03d", ultimoCodigo);

            SimpleDateFormat forma = new SimpleDateFormat("dd/MM/yyyy ");
            Date fecha = new Date();
            String formato = forma.format(fecha);

            int resultado = JOptionPane.showConfirmDialog(null, "Esta de acuerdo con esa calificación", "Confirmacion", JOptionPane.YES_NO_OPTION);

            if (resultado == JOptionPane.YES_OPTION) {
                ObjectSet<Calificar_evento> resul = base.queryByExample(new Calificar_evento(null,txtcedula.getText().trim(),null,0,null));

                if (!resul.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Ya ha calificado el evento.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                Calificar_evento califi = new Calificar_evento(codigo_evento, txtcedula.getText().trim(), nuevoCodigo, calificacion, fecha);
                base.store(califi);
                JOptionPane.showMessageDialog(null, "Gracias por apoyarnos, tu opinión nos ayuda a crecer");
                LimopiarCalificaion();

            } else if (resultado == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Escoje la calificación que darías al evento ");
                LimopiarCalificaion();

            }

        } finally {
            base.close();
        }
    }

    public void LimopiarCalificaion() {

        lbl1.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));
        lbl2.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));
        lbl3.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));
        lbl4.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));
        lbl5.setIcon(new ImageIcon("src\\imagenes\\Estrella vacia.png"));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lblEstrella1;
    private javax.swing.JLabel lblemoji;
    private javax.swing.JLabel txtcedula;
    // End of variables declaration//GEN-END:variables
}
