package Interfases;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Lenovo.User
 */
public class Cambio extends javax.swing.JPanel implements ActionListener {

    crud_tipo tipo = new crud_tipo();
    Cruds_Eventos event = new Cruds_Eventos();
    Reporte_eventos co = new Reporte_eventos();

    /**
     * Creates new form Cambio
     */
    public Cambio() {
        initComponents();
        contenedor.add(tipo);
        tipo.setVisible(true);
        event.setVisible(false);
        co.setVisible(false);

        desabilitarPanel();

        btnanterior.addActionListener(this);
        btnsiguente.addActionListener(this);
        btnconsulta.addActionListener(this);

    }

    public void desabilitarPanel() {
        if (tipo.isVisible()) {
            btnanterior.setEnabled(true);
            btnsiguente.setEnabled(true);
            btnconsulta.setEnabled(true);

        } else if (event.isVisible()) {
            btnanterior.setEnabled(true);
            btnsiguente.setEnabled(true);
            btnconsulta.setEnabled(true);

        } else if (co.isVisible()) {

            btnanterior.setEnabled(true);
            btnsiguente.setEnabled(true);
            btnconsulta.setEnabled(true);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contenedor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnanterior = new javax.swing.JButton();
        btnsiguente = new javax.swing.JButton();
        btnconsulta = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setMinimumSize(new java.awt.Dimension(923, 638));
        setPreferredSize(new java.awt.Dimension(923, 638));
        setLayout(new java.awt.BorderLayout());

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 12, true));
        contenedor.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnanterior.setText("Tipo de evento");
        btnanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanteriorActionPerformed(evt);
            }
        });
        jPanel2.add(btnanterior);

        btnsiguente.setText("Ingresar- modificar Evento");
        jPanel2.add(btnsiguente);

        btnconsulta.setText("Consultar Evento");
        jPanel2.add(btnconsulta);

        contenedor.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        add(contenedor, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnanteriorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnconsulta;
    private javax.swing.JButton btnsiguente;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {

        Object evt = e.getSource();
        if (evt.equals(btnanterior)) {
            event.setVisible(false);
            tipo.setVisible(true);

            co.setVisible(false);
            contenedor.add(tipo);
            contenedor.validate();

            desabilitarPanel();

        } else if (evt.equals(btnsiguente)) {
            event.setVisible(true);
            tipo.setVisible(false);

            co.setVisible(false);
            contenedor.add(event);
            contenedor.validate();

            desabilitarPanel();

        } else if (evt.equals(btnconsulta)) {
            event.setVisible(false);
            tipo.setVisible(false);

            co.setVisible(true);
            contenedor.add(co);
            contenedor.validate();

            desabilitarPanel();

        } 
    }
}
