/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfases;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Lenovo.User
 */
public class Cambio extends javax.swing.JPanel implements ActionListener {

    crud_tipo tipo = new crud_tipo();
    Cruds_Eventos event = new Cruds_Eventos();

    /**
     * Creates new form Cambio
     */
    public Cambio() {
        initComponents();
        contenedor.add(tipo);
        tipo.setVisible(true);
        event.setVisible(false);
        
        desabilitarPanel();
        
        btnanterior.addActionListener(this);
        btnsiguente.addActionListener(this);

    }
    
   
    public void desabilitarPanel(){
        if (tipo.isVisible()) {
            btnanterior.setEnabled(false);
            btnsiguente.setEnabled(true);
            
            
        }else if (event.isVisible()) {
             btnanterior.setEnabled(true);
            btnsiguente.setEnabled(false);
            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contenedor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnanterior = new javax.swing.JButton();
        btnsiguente = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        contenedor.setLayout(new java.awt.BorderLayout());

        btnanterior.setText("ANTERIOR");
        jPanel2.add(btnanterior);

        btnsiguente.setText("SIGUENTE");
        jPanel2.add(btnsiguente);

        contenedor.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        add(contenedor, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnsiguente;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {

        Object evt = e.getSource();
        if (evt.equals(btnanterior)) {
            event.setVisible(false);
            tipo.setVisible(true);
            contenedor.add(tipo);
            contenedor.validate();
            
            desabilitarPanel();
            
            
        }else if (evt.equals(btnsiguente)) {
            event.setVisible(true);
            tipo.setVisible(false);
            contenedor.add(event);
            contenedor.validate();
            
            desabilitarPanel();
            
            
        }
    }
}
