/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfases;

import Clases.Comentario;
import Clases.Evento;
import Clases.Imagen;
import Clases.Tipo_evento;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import com.db4o.query.Query;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo.User
 */
public class Mi_blog extends javax.swing.JPanel {

    String tipo = "", codigo = " ";
    byte[] foto;

    int longitudBytes;

    /**
     * Creates new form Mi_blog
     */
    public Mi_blog() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxeventos = new javax.swing.JComboBox<>();
        lbl1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fotolbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txachat = new javax.swing.JTextArea();
        txtcomentario = new javax.swing.JTextField();
        btnenviar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("MI BLOG");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 270, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("SELECCIONE UN EVENTO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 230, -1));

        cbxeventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxeventosMouseClicked(evt);
            }
        });
        jPanel2.add(cbxeventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 140, -1));

        lbl1.setBackground(new java.awt.Color(255, 255, 255));
        lbl1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 230, 120));

        jButton1.setText("SUBE UNA IMAGEN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 220, 20));

        fotolbl.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(fotolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 230, 110));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("REALIZA UN COMENTARIO");

        txachat.setColumns(20);
        txachat.setRows(5);
        jScrollPane1.setViewportView(txachat);

        btnenviar.setText("Enviar");
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtcomentario)
                .addGap(18, 18, 18)
                .addComponent(btnenviar)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcomentario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 560, 430));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, 290, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 132, 290, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 290, 10));

        jButton2.setText("SUBE UNA IMAGEN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 220, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxeventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxeventosMouseClicked
        // TODO add your handling code here:

        ObjectContainer base = Db4o.openFile(Inicio.direccion);
        cargar(base);
        ObtenerTipo();
        base.close();

    }//GEN-LAST:event_cbxeventosMouseClicked

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        // TODO add your handling code here:

        ObjectContainer base = Db4o.openFile(Inicio.direccion);

        String comentario = txtcomentario.getText().trim();
        if (comentario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un comentario");
        } else if (!comentario.isEmpty()) {

            btnenviar.setEnabled(true);
            try {

                Date fecha = new Date();

                Comentario comentario1 = new Comentario(comentario, null, Inicio.codigo, fecha);
                base.store(comentario1);

            } finally {

                base.close();
            }

            txachat.setText(Inicio.nombre + ":\n" + comentario + "\n Organizador:" + "\n Gracias por su comentario");
        }
    }//GEN-LAST:event_btnenviarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {

            JFileChooser se = new JFileChooser();
            se.setFileSelectionMode(JFileChooser.FILES_ONLY);
            int estado = se.showOpenDialog(null);
            if (estado == JFileChooser.APPROVE_OPTION) {
                try {
                    File archivo = se.getSelectedFile();
                    this.longitudBytes = (int) archivo.length();

                    // Leer la imagen seleccionada como bytes
                    byte[] buffer = new byte[this.longitudBytes];
                    try ( FileInputStream fis = new FileInputStream(archivo)) {
                        fis.read(buffer);
                    }

                    // Mostrar la imagen en el JLabel
                    Image icono = ImageIO.read(archivo).getScaledInstance(fotolbl.getWidth(), fotolbl.getHeight(), Image.SCALE_DEFAULT);
                    fotolbl.setIcon(new ImageIcon(icono));
                    fotolbl.updateUI();

                    // Asignar los bytes de la imagen a la variable "foto"
                    foto = buffer;
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, " No se selecciono una imagen ");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ObjectContainer base = Db4o.openFile(Inicio.direccion);

        crearImagen(base);

        base.close();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void crearImagen(ObjectContainer base) {

        try {

            ObjectSet<Imagen> resul = base.queryByExample(new Imagen(null, null, null, null));
            int ultimoCodigo = resul.size() + 1;

            // Formatear el código con ceros a la izquierda
            String cod = String.format("%03d", ultimoCodigo);
            // lblcod.setText(cod);

            // Verificar si ya existe una casa con el mismo código
            resul = base.queryByExample(new Imagen(cod, null, null, null));
            Imagen im = new Imagen(null, Inicio.codigo, cod, foto);
            base.store(im);
            JOptionPane.showMessageDialog(null, " Se guardo exitosamente, no te olvides de comentar  el evento");

            // Limpiar el JLabel (establecer su icono en un icono vacío)
            fotolbl.setIcon(new ImageIcon(new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB)));

        } finally {
            base.close();
        }
    }

    private byte[] obtenerBytesImagen() {
        JFileChooser se = new JFileChooser();
        se.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int estado = se.showOpenDialog(null);
        if (estado == JFileChooser.APPROVE_OPTION) {
            try {
                File archivo = se.getSelectedFile();
                this.longitudBytes = (int) archivo.length();

                // Leer la imagen seleccionada como bytes
                byte[] buffer = new byte[this.longitudBytes];
                try ( FileInputStream fis = new FileInputStream(archivo)) {
                    fis.read(buffer);
                }

                // Mostrar la imagen en un JLabel (opcional, solo para visualización)
                Image icono = ImageIO.read(archivo).getScaledInstance(fotolbl.getWidth(), fotolbl.getHeight(), Image.SCALE_DEFAULT);
                fotolbl.setIcon(new ImageIcon(icono));
                fotolbl.updateUI();

                return buffer;
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        return null;
    }

// Método que invoca obtenerBytesImagen() y asigna el arreglo de bytes a la variable "foto"
    public void seleccionarImagen() {
        foto = obtenerBytesImagen();
    }

    public void ObtenerTipo() {
        ObjectContainer base = Db4o.openFile(Inicio.direccion);

        try {
            Query q = base.query();
            q.constrain(Tipo_evento.class);
            q.descend("codigo_evento").constrain(cbxeventos.getSelectedItem());
            ObjectSet<Tipo_evento> result = q.execute();

            
            
            if (!result.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Si ingresa jJjjajajjaja");
                for (Tipo_evento servi : result) {
                    foto = servi.getData();

                    if (foto != null) {
                        ImageIcon icono = new ImageIcon(foto);
                        lbl1.setIcon(icono);
                    } else {
                        JOptionPane.showMessageDialog(null, "no se ha subido imagen al tipo de evento");
                    }

                }

            }
        } finally {
            base.close();
        }
    }

    public void cargar(ObjectContainer base) {

        try {
            cbxeventos.removeAllItems();
            Query query = base.query();
            query.constrain(Evento.class);

            ObjectSet<Evento> evento1 = query.execute();

            while (evento1.hasNext()) {

                Evento mie = evento1.next();
                tipo = mie.getTipo();
                codigo = mie.getCod_evento();
                System.out.println(tipo);

                cbxeventos.addItem(mie.getNombre());

            }

        } finally {

            base.close();

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenviar;
    private javax.swing.JComboBox<String> cbxeventos;
    private javax.swing.JLabel fotolbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTextArea txachat;
    private javax.swing.JTextField txtcomentario;
    // End of variables declaration//GEN-END:variables
}
