/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfases;

import Clases.Publico_p;
import Clases.Validaciones;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author ADMIN_01
 */
public class Publico extends javax.swing.JFrame {

    public static ArrayList<Publico_p> listaagentes = new ArrayList<>();

    public static ArrayList<Publico_p> codigoseliminados = new ArrayList<>();

    Boolean primeraMayusculaIngresada;

    public Publico() {
        initComponents();
        this.setLocationRelativeTo(null);
        agrupar();
        btncrear.setEnabled(false);
    }

    public void agrupar() {

        ButtonGroup botones = new ButtonGroup();
        botones.add(rbnMasculino);
        botones.add(rbnFemenino);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordPublico = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblcod = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateFechaNaci = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        rbnMasculino = new javax.swing.JRadioButton();
        rbnFemenino = new javax.swing.JRadioButton();
        btncrear = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPreferencias = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblcedula = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lblgenero = new javax.swing.JLabel();
        lblcelular = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        lblpreferencia = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(870, 630));
        setPreferredSize(new java.awt.Dimension(870, 630));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 12, true));
        jPanel1.setMinimumSize(new java.awt.Dimension(840, 570));
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cedula:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Telefono:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, 40));

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 180, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 180, -1));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 180, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 180, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel9.setText("REGISTRO PUBLICO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 260, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo Oficila de Eventos.PNG"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, -1, -1));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 180, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Contraseña:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        jPasswordPublico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPasswordPublico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordPublicoActionPerformed(evt);
            }
        });
        jPasswordPublico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordPublicoKeyReleased(evt);
            }
        });
        jPanel1.add(jPasswordPublico, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 180, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/REGRESAR.jpg"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 60, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Codigo Publico:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        lblcod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(lblcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 170, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Fecha de Nacimiento: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jDateFechaNaci.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateFechaNaciPropertyChange(evt);
            }
        });
        jPanel1.add(jDateFechaNaci, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 180, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Género:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 60, -1));

        rbnMasculino.setText("Masculino");
        rbnMasculino.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbnMasculinoStateChanged(evt);
            }
        });
        jPanel1.add(rbnMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        rbnFemenino.setText("Femenino");
        rbnFemenino.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbnFemeninoStateChanged(evt);
            }
        });
        jPanel1.add(rbnFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        btncrear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btncrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disco-flexible.png"))); // NOI18N
        btncrear.setText("Crear Cuenta ");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });
        jPanel1.add(btncrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 160, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Celular:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Preferencias: ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, 30));

        txtPreferencias.setColumns(20);
        txtPreferencias.setRows(5);
        txtPreferencias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPreferenciasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPreferenciasKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtPreferencias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 180, 120));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Dirección:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireccionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 180, -1));

        lblcedula.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 180, 20));

        lblnombre.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 180, 20));

        lblapellido.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 180, 20));

        lblemail.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 180, 20));

        lbltelefono.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbltelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 180, 20));

        lbldireccion.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbldireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 180, 20));

        lblfecha.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 444, 180, 20));

        lblgenero.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 180, 20));

        lblcelular.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 180, 20));

        lblcontraseña.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 180, 20));

        lblpreferencia.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblpreferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 180, 20));
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 180, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed

    }//GEN-LAST:event_txtCedulaActionPerformed
    public void crearPublico(ObjectContainer base) {
        try {

            if (!validarCampos()) {
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!validarRadioButton(rbnMasculino, rbnFemenino)) {
                JOptionPane.showMessageDialog(null, "Por favor, selecciona una opción en el grupo de género", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Obtener el último código
            ObjectSet<Publico_p> result = base.queryByExample(new Publico_p());
            int ultimoCodigo = result.size() + 1;

            // Formatear el código con ceros a la izquierda
            String cod = String.format("%03d", ultimoCodigo);
            lblcod.setText(cod);

            String seleccion = null;
            Date nacimiento = null;

            // establecer formato
            Date fecha = jDateFechaNaci.getDate();

            if (fecha != null) {
                seleccion = new SimpleDateFormat("dd/MM/yyyy").format(fecha);
            } else {
                System.out.println("Fecha no seleccionada");
            }

            // convertir el String seleccionado a Date
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            try {
                nacimiento = format.parse(seleccion);
                System.out.println("Date: " + nacimiento);

            } catch (ParseException e) {
                e.printStackTrace();
            }

            String sexo = rbnFemenino.isSelected() ? "Femenino" : (rbnMasculino.isSelected() ? "Masculino" : "");

            // Incremental code
            // Create a Publico_p instance with the cedula for checking existence
            Publico_p examplePublico = new Publico_p(null, null, null, null, null, null, txtCedula.getText().trim(), null, null, null, null, null, null, null, null);

            // Query the database to check for existing records
            ObjectSet<Publico_p> existingRecords = base.queryByExample(examplePublico);

            if (!existingRecords.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ya existe un Publico con la cédula ingresada.", "Error", JOptionPane.ERROR_MESSAGE);
                lblcedula.setText("Campo obligatorio");
                return;
            }

            Validar();

            // public Publico_p(String codigo_publico, String estado_registro, String preferencias_p, String contraseña, String codigo_encuesta, String codigo_cali_even, String cedula_persona, String cedula, String nombre, String apellido, String telefono, String correo, String direccion, String celular, Date fecchaNaci, String genero) {
            Publico_p mipublico = new Publico_p(cod, txtPreferencias.getText().trim(), jPasswordPublico.getText().trim(), null, null, null, txtCedula.getText().trim(), txtNombre.getText().trim(), txtApellido.getText().trim(), txtTelefono.getText().trim(), txtEmail.getText().trim(), txtDireccion.getText().trim(),
                    txtCelular.getText().trim(), nacimiento, sexo);

            base.store(mipublico);

            JOptionPane.showMessageDialog(null, " Se guardo los datos de forma correcta");
        } finally {
            base.close();

        }

        // spnedad.setValue(0);
        txtEmail.setText("".trim());
        jDateFechaNaci.setDate(null);
        txtCedula.setText("".trim());
        txtNombre.setText("".trim());
        txtApellido.setText("".trim());
        txtCelular.setText("".trim());
        txtTelefono.setText("".trim());
        lblcod.setText(" ".trim());
        txtDireccion.setText("".trim());
        jPasswordPublico.setText("");
        txtPreferencias.setText("");
        rbnFemenino.setSelected(false);
        rbnMasculino.setSelected(false);

    }

    private boolean validarRadioButton(JRadioButton... buttons) {
        for (JRadioButton button : buttons) {
            if (button.isSelected()) {
                return true;
            }
        }
        return false;
    }

    public boolean validarCampos() {
        Validaciones miValidaciones = new Validaciones();
        boolean ban_confirmar = true;

        if (txtCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la Cédula");
            ban_confirmar = false;
        } else if (!miValidaciones.validarCedula(txtCedula.getText())) {
            JOptionPane.showMessageDialog(this, "Cédula incorrecta. Ingrese de nuevo");
            ban_confirmar = false;
        }

        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el Nombre");
            ban_confirmar = false;
        } else if (!miValidaciones.ValidarNomApe(txtNombre.getText())) {
            JOptionPane.showMessageDialog(this, "Nombre incorrecto. Ingrese de nuevo");
            ban_confirmar = false;
        }

        if (txtApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el Apellido");
            ban_confirmar = false;
        } else if (!miValidaciones.ValidarNomApe(txtApellido.getText())) {
            JOptionPane.showMessageDialog(this, "Apellido incorrecto. Ingrese de nuevo");
            ban_confirmar = false;
        }

        if (txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el Correo");
            ban_confirmar = false;
        } else if (!miValidaciones.ValidarCorreo(txtEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Correo incorrecto. Ingrese de nuevo");
            ban_confirmar = false;
        }

        // Validar otros campos aquí...
        if (txtTelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el Telefono");
            ban_confirmar = false;
        } else if (!miValidaciones.validarTelefono(txtTelefono.getText())) {
            JOptionPane.showMessageDialog(this, "Telefono incorrecto. Ingrese de nuevo");
            ban_confirmar = false;
        }

        if (txtDireccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la Direccion");
            ban_confirmar = false;
        } else if (!miValidaciones.validarDireccion(txtDireccion.getText())) {
            JOptionPane.showMessageDialog(this, "Direccion incorrecta. Ingrese de nuevo");
            ban_confirmar = false;
        }

        if (jDateFechaNaci.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Ingrese una Fecha");
            ban_confirmar = false;
        } else {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String fechaComoCadena = sdf.format(jDateFechaNaci.getDate());

            if (!miValidaciones.validarFecha(fechaComoCadena)) {
                JOptionPane.showMessageDialog(this, "Fecha incorrecta. Ingrese de nuevo");
                ban_confirmar = false;
            }
        }

        if (txtCelular.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el Celular");
            ban_confirmar = false;
        } else if (!miValidaciones.validarCedula(txtCelular.getText())) {
            JOptionPane.showMessageDialog(this, "Celular incorrecto. Ingrese de nuevo");
            ban_confirmar = false;
        }

        if (txtPreferencias.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese las Preferencias");
            ban_confirmar = false;
        } else if (!miValidaciones.validarDireccion(txtPreferencias.getText())) {
            JOptionPane.showMessageDialog(this, "Preferencia incorrecta. Ingrese de nuevo");
            ban_confirmar = false;
        }

        return ban_confirmar;
    }

    public void Validar() {

        if (txtCedula.getText().trim().isEmpty()) {
            lblcedula.setText("Campo obligatorio");
        } else {
            lblcedula.setText("");
        }

        if (txtEmail.getText().trim().isEmpty()) {

            lblemail.setText("Campo obligatorio");
        } else {
            lblemail.setText(" ");
        }
        if (txtNombre.getText().trim().isEmpty()) {
            lblnombre.setText("Campo obligatorio");
        } else {
            lblnombre.setText("");
        }
        if (txtApellido.getText().trim().isEmpty()) {
            lblapellido.setText("Campo obligatorio");
        } else {
            lblapellido.setText(" ");
        }
        if (txtCelular.getText().trim().isEmpty()) {
            lblcelular.setText("Campo obligatorio");

        } else {
            lblcelular.setText("");

        }
        if (txtTelefono.getText().trim().isEmpty()) {
            lbltelefono.setText("Campo obligatorio");

        } else {
            lbltelefono.setText("");

        }

        if (txtPreferencias.getText().trim().isEmpty()) {
            lblpreferencia.setText("Campo obligatorio");

        } else {
            lblpreferencia.setText("");

        }
        if (txtDireccion.getText().trim().isEmpty()) {
            lbldireccion.setText("Campo obligatorio");

        } else {
            lbldireccion.setText("");
        }
        if (jPasswordPublico.getText().trim().isEmpty()) {
            lblcontraseña.setText("Campo obligatorio");

        } else {
            lblcontraseña.setText("");
        }
        if (jDateFechaNaci.getDate() == null) {
            lblfecha.setText("Campo requerido");

        } else {
            lblfecha.setText(" ");
        }

        if (rbnFemenino.isSelected()) {
            lblgenero.setText(" ");
        } else if (rbnMasculino.isSelected()) {
            lblgenero.setText(" ");

        } else if (!rbnFemenino.isSelected() || !rbnMasculino.isSelected()) {
            lblgenero.setText("Campo requerido");
        }

        if (jDateFechaNaci.getDate() == null || jPasswordPublico.getText().trim().isEmpty() || txtDireccion.getText().trim().isEmpty() || txtTelefono.getText().trim().isEmpty() || txtCelular.getText().trim().isEmpty()
                || (!rbnFemenino.isSelected() && !rbnMasculino.isSelected()) || txtApellido.getText().trim().isEmpty() || txtNombre.getText().trim().isEmpty() || txtCedula.getText().trim().isEmpty() || txtEmail.getText().trim().isEmpty()
                || txtPreferencias.getText().trim().isEmpty()) {
            btncrear.setEnabled(false);

        } else {
            btncrear.setEnabled(true);
        }
    }
    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtApellidoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Inicio le = new Inicio();
        le.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
//    
    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        // TODO add your handling code here:

        ObjectContainer base = Db4o.openFile(Inicio.direccion);

        crearPublico(base);
        base.close();
    }//GEN-LAST:event_btncrearActionPerformed

    private void jPasswordPublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordPublicoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jPasswordPublicoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDireccionActionPerformed

    private void jDateFechaNaciPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateFechaNaciPropertyChange
        // TODO add your handling code here:
        Validar();
    }//GEN-LAST:event_jDateFechaNaciPropertyChange

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        // Verificar si es un número y si la longitud actual es menor que 10
        if (!Character.isDigit(c) || txtCedula.getText().length() >= 10) {
            // Si no es un número o la longitud es mayor o igual a 10, se consume el evento para evitar que se agregue al campo de texto
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased
        // TODO add your handling code here:
        Validar();
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        Validar();
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyReleased
        // TODO add your handling code here:
        Validar();
    }//GEN-LAST:event_txtApellidoKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        Validar();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        // TODO add your handling code here:
        Validar();
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyReleased
        // TODO add your handling code here:
        Validar();
    }//GEN-LAST:event_txtDireccionKeyReleased

    private void rbnMasculinoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbnMasculinoStateChanged
        // TODO add your handling code here:
        Validar();
    }//GEN-LAST:event_rbnMasculinoStateChanged

    private void rbnFemeninoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbnFemeninoStateChanged
        // TODO add your handling code here:
        Validar();
    }//GEN-LAST:event_rbnFemeninoStateChanged

    private void jPasswordPublicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordPublicoKeyReleased
        // TODO add your handling code here:
        Validar();
    }//GEN-LAST:event_jPasswordPublicoKeyReleased

    private void txtPreferenciasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPreferenciasKeyReleased
        // TODO add your handling code here:
        Validar();
    }//GEN-LAST:event_txtPreferenciasKeyReleased

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String textoActual = txtNombre.getText();

        // Verificar si es una letra minúscula y si la longitud actual es menor que 20 y si no es un espacio en blanco
        if ((!Character.isLetter(c) || (Character.isLowerCase(c) && textoActual.length() >= 20) || c == ' ')) {
            // Si no es una letra minúscula, o la longitud es mayor o igual a 20, o el caracter es un espacio en blanco, se consume el evento para evitar que se agregue al campo de texto
            evt.consume();
        } else if (textoActual.length() == 0) {
            // Si es el primer caracter del campo de texto, verificar que sea mayúscula
            if (!Character.isUpperCase(c)) {
                // Si no es mayúscula, convertirla a mayúscula
                evt.setKeyChar(Character.toUpperCase(c));
                primeraMayusculaIngresada = true;
            }
        } else {
            // Si no es el primer caracter del campo de texto, verificar que sea minúscula
            char ultimoCaracter = textoActual.charAt(textoActual.length() - 1);
            if (Character.isUpperCase(ultimoCaracter)) {
                // Si es mayúscula, convertirla a minúscula
                evt.setKeyChar(Character.toLowerCase(c));
                primeraMayusculaIngresada = true;
            }
        }

    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        // Verificar si es una letra minúscula y si la longitud actual es menor que 50 y si no es un espacio en blanco
        if ((!Character.isLetter(c) || !Character.isLowerCase(c) && primeraMayusculaIngresada) || txtApellido.getText().length() >= 20 || c == ' ') {
            // Si no es una letra minúscula, o no es la primera letra mayúscula, o la longitud es mayor o igual a 50, o el caracter es un espacio en blanco, se consume el evento para evitar que se agregue al campo de texto
            evt.consume();
        } else if (txtApellido.getText().length() == 0) {
            // Si es el primer caracter del campo de texto, verificar que sea mayúscula
            if (!Character.isUpperCase(c)) {
                // Si no es mayúscula, convertirla a mayúscula
                evt.setKeyChar(Character.toUpperCase(c));
                primeraMayusculaIngresada = true;
            }
        } else {
            // Si no es el primer caracter del campo de texto, verificar que sea minúscula
            String textoActual = txtApellido.getText();
            char ultimoCaracter = textoActual.charAt(textoActual.length() - 1);
            if (Character.isUpperCase(ultimoCaracter)) {
                // Si es mayúscula, convertirla a minúscula
                evt.setKeyChar(Character.toLowerCase(c));
                primeraMayusculaIngresada = true;
            }
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        // Verificar si es un número y si la longitud actual es menor que 10
        if (!Character.isDigit(c) || txtTelefono.getText().length() >= 7) {
            // Si no es un número o la longitud es mayor o igual a 10, se consume el evento para evitar que se agregue al campo de texto
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped
    private boolean esCaracterEspecial(char caracter) {
        // Puedes ajustar esta lógica según los caracteres especiales que quieras permitir
        return "!@#$%^&*()_-+=<>?/".indexOf(caracter) != -1;
    }
    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        char letra = evt.getKeyChar();

// Verificar si es una letra y si es la primera letra
        if (Character.isLetter(letra) && txtDireccion.getText().trim().isEmpty()) {
            // Convertir la letra a mayúscula y agregarla al texto existente
            txtDireccion.setText(String.valueOf(Character.toUpperCase(letra)));
            evt.consume();  // Consumir el evento para evitar que la letra original se muestre
        } else if (Character.isLetter(letra) || Character.isSpaceChar(letra)) {
            // Verificar si es letra o espacio y agregar al texto en minúscula
            txtDireccion.setText(txtDireccion.getText() + Character.toLowerCase(letra));
            evt.consume();
        } else {
            evt.consume();
        }

// Limitar la longitud del texto a 20 caracteres
        if (txtDireccion.getText().length() > 80) {
            evt.consume();
        }

    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtPreferenciasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPreferenciasKeyTyped
        char letra = evt.getKeyChar();

// Verificar si es una letra y si es la primera letra
        if (Character.isLetter(letra) && txtPreferencias.getText().trim().isEmpty()) {
            // Convertir la letra a mayúscula y agregarla al texto existente
            txtPreferencias.setText(String.valueOf(Character.toUpperCase(letra)));
            evt.consume();  // Consumir el evento para evitar que la letra original se muestre
        } else if (Character.isLetter(letra) || Character.isSpaceChar(letra)) {
            // Verificar si es letra o espacio y agregar al texto en minúscula
            txtPreferencias.setText(txtPreferencias.getText() + Character.toLowerCase(letra));
            evt.consume();
        } else {
            evt.consume();
        }

// Limitar la longitud del texto a 20 caracteres
        if (txtPreferencias.getText().length() > 80) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPreferenciasKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Publico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Publico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Publico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Publico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Publico().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncrear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateFechaNaci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordPublico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblcelular;
    private javax.swing.JLabel lblcod;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblgenero;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblpreferencia;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JRadioButton rbnFemenino;
    private javax.swing.JRadioButton rbnMasculino;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtPreferencias;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
