/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfases;

import Clases.Evento;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import com.db4o.query.Query;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo.User
 */
public class Reporte_evento extends javax.swing.JPanel {

    public static ArrayList<Evento> Listaeventos = new ArrayList<>();

    /**
     * Creates new form Reporte_evento
     */
    public Reporte_evento() {
        initComponents();
    }

    public void actualizarDatos() {
        ObjectContainer base = Db4o.openFile(Inicio.direccion);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        AsignarRegistrosArray(base);

        // Limpia los datos de la tabla y actualiza los datos en la tabla con los nuevos registros del ArrayList
        tbeventos.setModel(new DefaultTableModel());

        String[] columnNames = {"CODIGO", "NOMBRE", "DESCRIPCION", "TIPO DE EVENTO", "PATROCINADOR", "FECHA DE INICIO", "HORA DE INICIO", "FECHA DE CLAUSURA", "HORA FINAL DEL EVENTO"};

        Object[][] data = new Object[Listaeventos.size()][9];

        for (int i = 0; i < Listaeventos.size(); i++) {
            data[i][0] = Listaeventos.get(i).getCod_evento();
            data[i][1] = Listaeventos.get(i).getNombre();
            data[i][2] = Listaeventos.get(i).getDescripcion();
            data[i][3] = Listaeventos.get(i).getTipo();

            data[i][4] = Listaeventos.get(i).getCodigo_patrocinador();

            data[i][5] = Listaeventos.get(i).getFecha_inicio() != null ? sdf.format(Listaeventos.get(i).getFecha_inicio()) : null;
            data[i][6] = Listaeventos.get(i).getHora_inicio();

            data[i][7] = Listaeventos.get(i).getFecha_fin()!= null ? sdf.format(Listaeventos.get(i).getFecha_fin()) : null;
            data[i][8] = Listaeventos.get(i).getHora_fin();
        }

        this.validate();
        tbeventos.repaint();

        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        tbeventos.setModel(model);

        base.close();
    }

    public void AsignarRegistrosArray(ObjectContainer base) {

        Query query = base.query();
        query.constrain(Evento.class);
        ObjectSet<Evento> eventos = query.execute();

        if (eventos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se ha ingresado eventos");
        }

        // Elimina todos los elementos del ArrayList existente
        Listaeventos.clear();

        // Agrega los nuevos registros al ArrayList
        for (Evento mievento : eventos) {
            Listaeventos.add(mievento);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbeventos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbeventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jScrollPane1.setViewportView(tbeventos);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("REPORTE GENERAL DE EVENTOS  MUNICIPALES");

        jButton1.setText("ACTUALIZAR REPORTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 790, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        actualizarDatos();

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbeventos;
    // End of variables declaration//GEN-END:variables
}
